name: Run Java Maven Script Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Allows manual trigger too

jobs:
  run-java-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'   # or whatever version you're using

      - name: Run Maven script
        run: test -Dsurefire.suiteXmlFiles=testng.xml
